spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: 7a6iA4w1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: NrEveu+r+hvL0/Y6wRY8f10PQTBABGjh7NURgAACwWvgeNF22Lvr8qfRrHcCQQFF
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

